import { ParticleConfig } from '../config/ParticleConfig';

export class ParticlePresets {
    static fire(): ParticleConfig {
        return {
            delay: 0,
            duration: 0,
            timeScale: 1,
            emissionRadius: 20,
            particleCount: 200,
            emissionRate: 100,
            variety: 30,
            lifeMin: 0.5,
            lifeMax: 1.5,
            speedMin: 30,
            speedMax: 80,
            angle: 270,
            spread: 45,
            scaleMin: 0.3,
            scaleMax: 1.2,
            scaleStart: 1,
            scaleEnd: 0,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 45,
            massMin: 0.5,
            massMax: 1,
            color: '#ff6600',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: -50,
            windX: 10,
            windY: 0,
            drag: 0.02,
            alphaStart: 1,
            alphaEnd: 0,
            colorStart: '#ffaa00',
            colorEnd: '#ff0000',
            physicsRadius: 5,
            bounce: 0.2,
            friction: 0.1,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: false,
            killOffscreen: true,
        };
    }

    static smoke(): ParticleConfig {
        return {
            delay: 0,
            duration: 0,
            timeScale: 1,
            emissionRadius: 15,
            particleCount: 150,
            emissionRate: 30,
            variety: 40,
            lifeMin: 2,
            lifeMax: 4,
            speedMin: 20,
            speedMax: 50,
            angle: 270,
            spread: 30,
            scaleMin: 0.5,
            scaleMax: 2,
            scaleStart: 0.5,
            scaleEnd: 2,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 20,
            massMin: 0.3,
            massMax: 0.8,
            color: '#808080',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: -30,
            windX: 15,
            windY: 0,
            drag: 0.01,
            alphaStart: 0.6,
            alphaEnd: 0,
            colorStart: '#ffffff',
            colorEnd: '#333333',
            physicsRadius: 8,
            bounce: 0.1,
            friction: 0.2,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: false,
            killOffscreen: true,
        };
    }

    static explosion(): ParticleConfig {
        return {
            delay: 0,
            duration: 500,
            timeScale: 1,
            emissionRadius: 5,
            particleCount: 500,
            emissionRate: 1000,
            variety: 50,
            lifeMin: 0.5,
            lifeMax: 2,
            speedMin: 100,
            speedMax: 300,
            angle: 0,
            spread: 360,
            scaleMin: 0.5,
            scaleMax: 1.5,
            scaleStart: 1,
            scaleEnd: 0.2,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 180,
            massMin: 1,
            massMax: 3,
            color: '#ffaa00',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: 100,
            windX: 0,
            windY: 0,
            drag: 0.05,
            alphaStart: 1,
            alphaEnd: 0,
            colorStart: '#ffff00',
            colorEnd: '#ff0000',
            physicsRadius: 5,
            bounce: 0.5,
            friction: 0.3,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: true,
            killOffscreen: false,
        };
    }

    static sparkles(): ParticleConfig {
        return {
            delay: 0,
            duration: 0,
            timeScale: 1,
            emissionRadius: 50,
            particleCount: 100,
            emissionRate: 20,
            variety: 20,
            lifeMin: 0.5,
            lifeMax: 1.5,
            speedMin: 10,
            speedMax: 30,
            angle: 270,
            spread: 360,
            scaleMin: 0.3,
            scaleMax: 0.8,
            scaleStart: 1,
            scaleEnd: 0,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 360,
            massMin: 0.1,
            massMax: 0.5,
            color: '#ffff00',
            shape: 'star',
            texture: null,
            gravityX: 0,
            gravityY: 20,
            windX: 0,
            windY: 0,
            drag: 0.01,
            alphaStart: 1,
            alphaEnd: 0,
            colorStart: '#ffffff',
            colorEnd: '#ffff00',
            physicsRadius: 3,
            bounce: 0.8,
            friction: 0.1,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: false,
            killOffscreen: true,
        };
    }

    static rain(): ParticleConfig {
        return {
            delay: 0,
            duration: 0,
            timeScale: 1,
            emissionRadius: 200,
            particleCount: 300,
            emissionRate: 100,
            variety: 10,
            lifeMin: 2,
            lifeMax: 3,
            speedMin: 200,
            speedMax: 300,
            angle: 90,
            spread: 5,
            scaleMin: 0.2,
            scaleMax: 0.5,
            scaleStart: 1,
            scaleEnd: 1,
            rotationMin: 0,
            rotationMax: 0,
            rotationSpeed: 0,
            massMin: 1,
            massMax: 2,
            color: '#88ccff',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: 200,
            windX: 20,
            windY: 0,
            drag: 0,
            alphaStart: 0.7,
            alphaEnd: 0.7,
            colorStart: '#88ccff',
            colorEnd: '#88ccff',
            physicsRadius: 2,
            bounce: 0.1,
            friction: 0,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: true,
            killOffscreen: true,
        };
    }

    static snow(): ParticleConfig {
        return {
            delay: 0,
            duration: 0,
            timeScale: 1,
            emissionRadius: 200,
            particleCount: 200,
            emissionRate: 30,
            variety: 20,
            lifeMin: 5,
            lifeMax: 8,
            speedMin: 20,
            speedMax: 50,
            angle: 90,
            spread: 20,
            scaleMin: 0.3,
            scaleMax: 0.8,
            scaleStart: 1,
            scaleEnd: 1,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 30,
            massMin: 0.3,
            massMax: 0.8,
            color: '#ffffff',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: 30,
            windX: 10,
            windY: 0,
            drag: 0.02,
            alphaStart: 0.9,
            alphaEnd: 0.9,
            colorStart: '#ffffff',
            colorEnd: '#ffffff',
            physicsRadius: 4,
            bounce: 0.2,
            friction: 0.1,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: true,
            killOffscreen: true,
        };
    }

    static magicPortal(): ParticleConfig {
        return {
            delay: 0,
            duration: 0,
            timeScale: 1,
            emissionRadius: 80,
            particleCount: 300,
            emissionRate: 60,
            variety: 30,
            lifeMin: 1,
            lifeMax: 2,
            speedMin: 40,
            speedMax: 100,
            angle: 0,
            spread: 360,
            scaleMin: 0.3,
            scaleMax: 1,
            scaleStart: 1,
            scaleEnd: 0,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 180,
            massMin: 0.5,
            massMax: 1.5,
            color: '#aa00ff',
            shape: 'star',
            texture: null,
            gravityX: 0,
            gravityY: 0,
            windX: 0,
            windY: 0,
            drag: 0.03,
            alphaStart: 1,
            alphaEnd: 0,
            colorStart: '#ff00ff',
            colorEnd: '#0000ff',
            physicsRadius: 5,
            bounce: 0.5,
            friction: 0.1,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: false,
            killOffscreen: true,
        };
    }

    static bloodSplatter(): ParticleConfig {
        return {
            delay: 0,
            duration: 200,
            timeScale: 1,
            emissionRadius: 10,
            particleCount: 100,
            emissionRate: 500,
            variety: 40,
            lifeMin: 1,
            lifeMax: 3,
            speedMin: 100,
            speedMax: 250,
            angle: 0,
            spread: 360,
            scaleMin: 0.4,
            scaleMax: 1.2,
            scaleStart: 1,
            scaleEnd: 0.8,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 90,
            massMin: 1,
            massMax: 3,
            color: '#880000',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: 300,
            windX: 0,
            windY: 0,
            drag: 0.1,
            alphaStart: 1,
            alphaEnd: 0.5,
            colorStart: '#ff0000',
            colorEnd: '#440000',
            physicsRadius: 5,
            bounce: 0.3,
            friction: 0.5,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: true,
            killOffscreen: false,
        };
    }

    static dustCloud(): ParticleConfig {
        return {
            delay: 0,
            duration: 1000,
            timeScale: 1,
            emissionRadius: 30,
            particleCount: 150,
            emissionRate: 150,
            variety: 35,
            lifeMin: 1,
            lifeMax: 2.5,
            speedMin: 30,
            speedMax: 80,
            angle: 0,
            spread: 360,
            scaleMin: 0.5,
            scaleMax: 1.5,
            scaleStart: 0.5,
            scaleEnd: 2,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 45,
            massMin: 0.5,
            massMax: 1,
            color: '#aa8855',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: -20,
            windX: 30,
            windY: 0,
            drag: 0.05,
            alphaStart: 0.7,
            alphaEnd: 0,
            colorStart: '#ccaa77',
            colorEnd: '#886644',
            physicsRadius: 6,
            bounce: 0.2,
            friction: 0.3,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: false,
            killOffscreen: true,
        };
    }

    static electricShock(): ParticleConfig {
        return {
            delay: 0,
            duration: 800,
            timeScale: 1,
            emissionRadius: 5,
            particleCount: 200,
            emissionRate: 250,
            variety: 60,
            lifeMin: 0.2,
            lifeMax: 0.6,
            speedMin: 50,
            speedMax: 200,
            angle: 0,
            spread: 360,
            scaleMin: 0.3,
            scaleMax: 0.8,
            scaleStart: 1,
            scaleEnd: 0,
            rotationMin: 0,
            rotationMax: 360,
            rotationSpeed: 720,
            massMin: 0.1,
            massMax: 0.5,
            color: '#00ffff',
            shape: 'circle',
            texture: null,
            gravityX: 0,
            gravityY: 0,
            windX: 0,
            windY: 0,
            drag: 0.08,
            alphaStart: 1,
            alphaEnd: 0,
            colorStart: '#ffffff',
            colorEnd: '#0088ff',
            physicsRadius: 3,
            bounce: 0.9,
            friction: 0,
            killOnCollision: false,
            collisionLayer: 0,
            enableBounds: false,
            killOffscreen: true,
        };
    }

    static getPreset(name: string): ParticleConfig | null {
        switch (name) {
            case 'fire':
                return this.fire();
            case 'smoke':
                return this.smoke();
            case 'explosion':
                return this.explosion();
            case 'sparkles':
                return this.sparkles();
            case 'rain':
                return this.rain();
            case 'snow':
                return this.snow();
            case 'magicPortal':
                return this.magicPortal();
            case 'bloodSplatter':
                return this.bloodSplatter();
            case 'dustCloud':
                return this.dustCloud();
            case 'electricShock':
                return this.electricShock();
            default:
                return null;
        }
    }
}
